= DataStax Docs UI
// Variables:
:current-release:
// Settings:
:!example-caption:
:experimental:
:hide-uri-scheme:
:toc: macro
ifdef::env-github[]
:icons: font
:toc-title: Contents
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:badges:
endif::[]
// Project URLs:
:url-project: https://github.com/riptano/docs-ui
:url-preview: https://riptano.github.io/docs-ui/main
// :url-ci-pipelines: {url-project}/pipelines
// :img-ci-status: {url-project}/badges/master/pipeline.svg
:url-docs-home: https://github.com/riptano/docs-home
:url-datastax: https://datastax.com
:url-datastax-docs: https://docs.datastax.com
:url-datastax-docs-repo: https://github.com/riptano/docs-site
:url-coppi: https://coppi.aws.dsinternal.org
:url-docs-preview: http://docs-preview.datastax.com
:url-tailwind-readme: src/css/tailwind/README.adoc
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-antora-ui-docs: https://docs.antora.org/antora-ui-default/
:url-antora-default-ui: https://gitlab.com/antora/antora-ui-default
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/nvm-sh/nvm
:url-nvm-install: {url-nvm}#installing-and-updating
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
:url-create-release: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

// image:{img-ci-status}[CI Status (GitLab CI), link={url-ci-pipelines}]
// ifdef::badges[]
// image:https://img.shields.io/static/v1?label=release&amp;message={current-release}&amp;color=blue[Latest Release,link={url-project}/releases/download/{current-release}/ui-bundle.zip,format=svg]
// endif::[]

This project is used to develop and distribute the UI template for {url-datastax-docs}.
It is a fork of the {url-antora-default-ui}[Antora Default UI] that has been customized for our needs.

The repository itself produces a UI bundle that can be applied when generating a static documentation site using {url-antora}[Antora] -- in our case, we apply it when generating {url-datastax-docs-repo}[docs-site].
The UI bundle contains the HTML templates (layouts, partials, and helpers), CSS, JavaScript, fonts, and (site-wide) images.
As such, it provides both the visual theme and user interactions for the documentation site.

You can see a preview of the DataStax Docs UI at {url-preview}.


toc::[]

[#use-the-ui]
== Use the DataStax Docs UI

To use the DataStax Docs UI with Antora, add the following configuration to your playbook file:

[source,yaml]
----
ui:
  bundle:
    url: https://github.com/riptano/ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
----

[NOTE]
====
The `snapshot` flag tells Antora to fetch the UI when the `--fetch` command-line flag is present.
This setting is required because updates to the UI bundle are pushed to the same URL.
If the URL were to be unique, this setting would not be required.
====

Read on to learn how to develop the UI.

== Development quickstart

This section offers a basic tutorial to teach you how to set up the UI project, preview it locally, and bundle it for use with Antora.
A more comprehensive tutorial can be found in the documentation at {url-antora-ui-docs}.

[#prerequisites]
=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-nodejs}[Node.js] (commands: `node` and `npm`)
* {url-gulp}[Gulp CLI] (command: `gulp`)

==== git

First, make sure you have git installed.

[source,shell]
----
git --version
----

If not, {url-git-dl}[download and install] the git package for your system.

==== Node.js

Next, make sure that you have Node.js installed (which also provides npm).

[source,shell]
----
node --version
----

If this command fails with an error, you don't have Node.js installed.
If the command doesn't report an https://nodejs.org/en[LTS version] of Node.js, it means you don't have a suitable version of Node.js installed.

While you can install Node.js from the official packages, we strongly recommend that you use {url-nvm}[nvm] (Node Version Manager) to manage your Node.js installation(s).
Follow the {url-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node.js LTS using the following command:

[source,shell]
----
nvm install --lts
----

You can switch to this version of Node.js at any time using the following command:

[source,shell]
----
nvm use --lts
----

To make Node.js LTS the default in new terminals, type:

[source,shell]
----
nvm alias default node
----

Now that you have Node.js installed, you can proceed with installing the Gulp CLI.

==== Gulp CLI

You'll need the Gulp command-line interface (CLI) to run the build.
The Gulp CLI package provides the `gulp` command which, in turn, executes the version of Gulp declared by the project.

You can install the Gulp CLI globally (which resolves to a location in your user directory if you're using nvm) using the following command:

[source,shell]
----
npm install -g gulp-cli
----

Verify the Gulp CLI is installed and on your PATH by running:

[source,shell]
----
gulp --version
----

If you prefer to install global packages using Yarn, run this command instead:

[source,shell]
----
yarn global add gulp-cli
----

Alternately, you can use the `gulp` command that is installed by the project's dependencies.

[source,shell]
----
npx --offline gulp --version
----

Now that you have the prerequisites installed, you can fetch and build the UI project.

=== Clone and initialize the UI project

Clone the default UI project using git:

[source,shell,subs=attributes+]
----
git clone {url-project} &&
cd "`basename $_`"
----

The example above clones the DataStax Docs UI project and then switches to the project folder on your filesystem.
Stay in this project folder when executing all subsequent commands.

Use npm to install the project's dependencies inside the project.
In your terminal, execute the following command:

[source,shell]
----
npm install
----

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle and should _not_ be committed to the source control repository.

[TIP]
====
If you prefer to install packages using Yarn, run this command instead:

[source,shell]
----
yarn
----
====

=== Preview the UI

The default UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

[source,shell]
----
gulp preview
----

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

[#create-bundle]
=== Package for use with Antora

If you need to package the UI so you can use it to generate the documentation site locally, run the following command:

[source,shell]
----
gulp bundle
----

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can point Antora at the local path to this bundle using the `--ui-bundle-url` command-line option or the https://docs.antora.org/antora/latest/playbook/ui-bundle-url/#url-key[`ui.bundle.url`] key in the site playbook.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

[source,shell]
----
gulp bundle:pack
----

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

==== Source maps

The build consolidates all the CSS and client-side JavaScript into combined files, [.path]_site.css_ and [.path]_site.js_, respectively, in order to reduce the size of the bundle.
{url-source-maps}[Source maps] correlate these combined files with their original sources.

This "`source mapping`" is accomplished by generating additional map files that make this association.
These map files sit adjacent to the combined files in the build folder.
The mapping they provide allows the debugger to present the original source rather than the obfuscated file, an essential tool for debugging.

In preview mode, source maps are enabled automatically, so there's nothing you have to do to make use of them.
If you need to include source maps in the bundle, you can do so by setting the `SOURCEMAPS` environment variable to `true` when you run the bundle command:

[source,shell]
----
SOURCEMAPS=true gulp bundle
----

In this case, the bundle will include the source maps, which can be used for debugging your production site.

==== Using TailwindCSS

This project uses TailwindCSS. To learn more see xref:{url-tailwind-readme}[TailwindCSS README].

== Release the UI bundle

Once you're satisfied with the changes you've made to the UI, you'll need to open a pull request to merge your changes into the `main` branch.
After your changes have been reviewed and merged, you can then choose to make those changes available in the production UI by publishing a new release to this repository and attaching the latest `ui-bundle.zip` file.

=== Bundle release procedure

. Start by making sure you've completed the <<prerequisites>>.

. Create the release commit.
+
Edit https://github.com/riptano/docs-ui/blob/bdf6484e46f41cff17238a7ef5aeae5368622d2c/README.adoc?plain=1#L3[README.adoc] directly in GitHub and increment the `:current-release:` attribute to the next version number.
+
[source,asciidoc]
----
:current-release: prod-* <.>
----
<.>  Add +1 to the version number
+
This should be the only change in the commit, and the commit message should take the form of *Release prod-*.
If you have Admin privileges to the repository, you can commit the changes directly to `main`.
Otherwise, you'll need to open a PR.

. Once the release commit is merged, open your local copy of the repository in a terminal and retrieve the latest changes from `main`.
+
[source,shell]
----
git switch main && git pull
----

. Pack the UI bundle as described in <<create-bundle>>.
+
[source,shell]
----
gulp bundle
----

. Create a new release (see {url-create-release}[GitHub documentation]).
.. Create a new tag named after the new version (e.g., `prod-2`).
The tag needs to target the `main` branch.
.. Make sure the *Title* of the release is the same name as the tag.
(The release title and the tag name should always be made the same, as it makes releases easier to identify.)
.. Instead of manually adding a description for the release, just click *Generate release notes*.
This automatically adds a description that highlights the functional changes that have been added since the last release.
.. Attach the UI bundle (`ui-bundle.zip`) as a release asset.
.. (Optional) Check the box labeled *This is a pre-release* if you don't want the release to be generally available.
+
Selecting this option is helpful if you want to publish a new UI bundle for testing purposes.
You can edit the release later to remove the *Pre-release* label if desired.
.. When you're ready, publish the release.

Once the new release is published, the attached bundle can then be downloaded from the repository using a unique URL found on the {url-project}/releases[releases page].

[IMPORTANT]
====
All production builds of the DataStax docs are configured to pull the latest, _non-pre-release_ UI bundle.
Once you've publish a new release, all subsequent site builds that use the configuration described in <<use-the-ui>> will consume the new UI bundle.
====


== Copyright and license

=== Software

Original Copyright (C) 2017-present {url-opendevise}[OpenDevise Inc.] and the {url-antora}[Antora Project].

Modifications and additions Copyright (C) 2023-present {url-datastax}[DataStax Inc.].

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

=== Branding and design

Copyright (C) {url-datastax}[DataStax Inc.] 2023-present.
All rights reserved.
