= DataStax Docs
:page-layout: home

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="flex rounded bg-level1 gap-6 mt-12 py-4 px-2 -mx-2 lg:px-4 lg:-mx-4 items-center">
  <div class="flex flex-col gap-6 max-w-2xl">
    
    <h2 class="discrete !m-0">Astra DB Serverless</h2>
    
    <p>Astra DB Serverless by DataStax provides the tools developers need to create robust AI applications, featuring strong APIs, real-time data processing, and easy integration with other systems.</p>

    <div class="flex gap-6">
      <span class="text-secondary text-caption font-display flex gap-2 items-center"><i class="icon material-icons text-2xl">handyman</i> Vector Search</span>
      <span class="text-secondary text-caption font-display flex gap-2 items-center"><i class="icon material-icons text-2xl">handyman</i> Modern APIs</span>
      <span class="text-secondary text-caption font-display flex gap-2 items-center"><i class="icon material-icons text-2xl">handyman</i> Native Integrations</span>
    </div>
    
    <div class="flex gap-4">
      xref:astra-db-serverless:get-started:quickstart.adoc[Quickstart <i class="material-icons icon ml-1 group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i>,role="btn btn-primary btn-solid group"]
      https://astra.datastax.com[Try Astra^,role="btn btn-neutral btn-outlined"]
    </div>

  </div>
  <div class="hidden lg:flex relative -my-12 ml-6">
++++

[source,python,subs="verbatim,quotes",role="nolang inverse-theme [&_.source-toolbox]:hidden rounded !m-0 [&_pre]:!py-6"]
----

from astrapy import DataAPIClient

# connect to a database
database = 
  DataAPIClient(*TOKEN*).get_database_by_api_endpoint(*URL*)

# Ingest vectors into your collection
collection = database.test_collection
collection.insert_many(documents=*DOCUMENTS*)

# Find the closest vectors
collection.find(vector=[0.15, 0.1, 0.1, 0.35, 0.55])

----

[subs="macros,attributes"]
++++
  </div>
</div>

<h3 class="discrete !mt-12 !mb-10">Popular Products</h3>

<div class="grid gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
  
  xref:astra-db-serverless::index.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">handyman</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">Astra DB Serverless</h4>
        <p class="text-tertiary">Scale with cloud-native databases</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

  xref:ragstack::index.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">timer</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">RAGStack</h4>
        <p class="text-tertiary">Enterprise RAG</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

  xref:dse:getting-started:get-started-dse.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">business</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">DSE</h4>
        <p class="text-tertiary">Enterprise scalability and performance</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

  xref:mission-control::index.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">space_dashboard</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">Mission Control</h4>
        <p class="text-tertiary">Manage your data ecosystem</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

  xref:astra-streaming:getting-started:index.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">air</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">Astra Streaming</h4>
        <p class="text-tertiary">Efficient data streaming</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

  xref:luna-cassandra::index.adoc[
    <div class="w-full h-full absolute rounded bg-gradient-to-r from-[#6B1C96\] via-[#D90036\] to-[#FFCA0B\] blur opacity-0 group-hover:opacity-30 dark:group-hover:opacity-50 transition-opacity duration-300"></div>
    <div class="relative h-full p-2 md:p-4 text-primary rounded border flex items-center gap-3 bg-body transition-colors group-hover:border-[var(--ds-primary-outlined-hover-border)\] duration-300">
      <div class="w-10 h-10 p-3 rounded bg-level1 flex items-center justify-center"><i class="icon material-icons">nights_stay</i></div>
      <div>
        <h4 class="discrete !m-0 !text-primary">Luna Support</h4>
        <p class="text-tertiary">Expertise and support for DataStax products</p>
      </div>
    </div>
  ,role="!no-underline relative group"]

</div>

<div class="mt-12 grid gap-10 md:grid-cols-2 md:grid-rows-[min-content_repeat(3,1fr)] md:grid-flow-col">

  <h3 class="pb-4 border-b !m-0">Latest Additions<i class="material-icons icon text-2xl mr-2">new_label</i></h3>

  xref:astra-db-serverless:databases:load-data.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Loading data into Astra DB databases
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          Astra DB
        </span>
      </h4>
      <p class="text-tertiary">++Use the Astra DB Data Loader to load data in your database from a variety of sources, including CSV files, sample datasets, and Amazon DynamoDB.++</p>
      <p class="!text-link">Read Loading data into Astra DB databases <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]

  xref:ragstack:intro-to-rag:evaluation.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Optimizing Query Performance
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          RAGStack
        </span>
      </h4>
      <p class="text-tertiary">++Improve the efficiency of your queries on AI-ready cloud databases with best practices for indexing and query tuning.++</p>
      <p class="!text-link">Read Optimizing Query Performance <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]

  xref:astra-db-serverless::index.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Securing Database Connections
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          Astra DB
        </span>
      </h4>
      <p class="text-tertiary">++Learn how to secure connections to your AI-ready cloud database using SSL encryption and access control methods.++</p>
      <p class="!text-link">Read Securing Database Connections <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]

  <h3 class="pb-4 border-b !m-0">Working with AI/ML <i class="material-icons icon text-2xl mr-2">smart_toy</i></h3>

  xref:astra-db-serverless::index.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Automating Backups and Recovery
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          Astra DB
        </span>
      </h4>
      <p class="text-tertiary">++Set up automated backups for your cloud database and learn how to quickly recover your data in case of loss or corruption.++</p>
      <p class="!text-link">Read Automating Backups and Recovery <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]

  xref:astra-db-serverless::index.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Monitoring and Alerts
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          Mission Control
        </span>
      </h4>
      <p class="text-tertiary">++Monitor the health and performance of your cloud database with real-time analytics and set up alerts for potential issues.++</p>
      <p class="!text-link">Read Monitoring and Alerts <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]

  xref:astra-db-serverless::index.adoc[
    <div class="py-4 -my-4 px-2 -mx-2 lg:px-4 lg:-mx-4 rounded flex flex-col grow gap-3 transition-colors group-hover:bg-level1">
      <h4 class="discrete !m-0 !text-primary text-display pb-2">
        Scaling Your Database
        <span class="ml-1 py-1 -my-1 px-2 bg-level1 text-nowrap rounded color-primary text-caption font-sans border border-transparent group-hover:border-[var(--ds-divider)\] transition-colors">
          Astra DB
        </span>
      </h4>
      <p class="text-tertiary">++Scale your AI-ready cloud database vertically or horizontally to meet changing workload demands and optimize performance.++</p>
      <p class="!text-link">Read Scaling Your Database <i class="material-icons icon group-hover:translate-x-1 transition-transform duration-300">arrow_forward</i></p>
    </div>
  ,role="!no-underline group flex flex-col"]
</div>

<div class="mt-12 grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-4">
  
  https://www.datastax.com/[
    <i class="material-icons icon text-2xl text-[var(--ds-text-placeholder)\] group-hover:color-primary transition-colors duration-300">home</i>
    <h4 class="discrete !m-0 !text-primary text-display">DataStax Home</h4>
    <p class="!text-link">Go to the DataStax website</p>
  ^,role="!no-underline group after:hidden rounded bg-level1 p-4 flex flex-col gap-1 hover:bg-[var(--ds-primary-soft-bg)\] transition-colors duration-300"]

  xref:glossary::index.adoc[
    <i class="material-icons icon text-2xl text-[var(--ds-text-placeholder)\] group-hover:color-primary transition-colors duration-300">menu_book</i>
    <h4 class="discrete !m-0 !text-primary text-display">Glossary</h4>
    <p class="!text-link">Review common terms</p>
  ,role="!no-underline group after:hidden rounded bg-level1 p-4 flex flex-col gap-1 hover:bg-[var(--ds-primary-soft-bg)\] transition-colors duration-300"]

  https://www.ibm.com/mysupport/s/[
    <i class="material-icons icon text-2xl text-[var(--ds-text-placeholder)\] group-hover:color-primary transition-colors duration-300">support</i>
    <h4 class="discrete !m-0 !text-primary text-display">Support</h4>
    <p class="!text-link">Access support resources</p>
  ^,role="!no-underline group after:hidden rounded bg-level1 p-4 flex flex-col gap-1 hover:bg-[var(--ds-primary-soft-bg)\] transition-colors duration-300"]

  https://downloads.datastax.com/#enterprise[
    <i class="material-icons icon text-2xl text-[var(--ds-text-placeholder)\] group-hover:color-primary transition-colors duration-300">downloading</i>
    <h4 class="discrete !m-0 !text-primary text-display">Downloads</h4>
    <p class="!text-link">Install files and drivers</p>
  ^,role="!no-underline group after:hidden rounded bg-level1 p-4 flex flex-col gap-1 hover:bg-[var(--ds-primary-soft-bg)\] transition-colors duration-300"]

</div>
++++
