= DataStax Astra Vector
:page-layout: landing

Efficiently store and query vector embeddings for better similarity search. If you're new, read our xref:ROOT:templates/examples/concepts.adoc[introduction to vector databases].

[.ds-feature]
== Get Started
--
Dive straight into Astra Vector with this concise guide tailored for developers. These essential steps will walk you through the setup process, ensuring you're up and running quickly.

[.ds-feature-button]
xref:ROOT:templates/examples/quickstart.adoc[Quick Start,role="ds-button ds-button\--color-neutral ds-button\--variant-outlined"] · https://astra.datastax.com[Create Astra Account^,role="ds-button ds-button\--color-neutral ds-button\--variant-outlined"]
--

[.ds-feature-code,python]
----
import vector

# Create a new vector database
db = vector.Database("my_vector_db")

# Ingest vectors into your database
db.ingest("s3://vector-embeddings-bucket/")

# Find the closest vectors
query_vector = [0.9, 2.2, 2.8]
results = db.query(query_vector, limit=3)
----

[.ds-row.noline]
== Explore Docs

=== Guides

Concise how-tos of common tasks with Astra.

* link:{#}[Load vector data]
* link:{#}[Explore my data]
* link:{#}[Manage my embeddings]

=== Tutorials

Dive into step-by-step lessons to master the essentials.

* link:{#}[Build a chatbot]
* link:{#}[Enhance a recommendation system]
* link:{#}[Write an AI agent]

=== Clients

Explore dedicated applications built to enhance your experience.

* link:{#}[How do I use the Python client]
* link:{#}[How do I use the Node.js client]
* link:{#}[Connect using the JSON API]

=== Integrations

Seamlessly connect with your favorite tools and platforms

* link:{#}[Connect to OpenAI]
* link:{#}[Connect to LangChain]
* link:{#}[Connect to LlamaIndex]

[.ds-row.noline]
== What's New?

=== DataStax Astra Integrations

Amplify your development potential with integrations crafted for popular platforms and languages. Dive deep into how DataStax Astra seamlessly interacts with Python, Java, Node.js, and more.

link:{#}[Explore Astra Integrations]


=== Scaling Production Workloads

Equip yourself with the tools and techniques to scale your applications effectively. Meet the demands of today while preparing for the challenges of tomorrow.

link:{#}[Discover Scalability Techniques]

=== Securing Your Vector Databases

Prioritize the protection of your invaluable data. Explore advanced strategies and tools designed to safeguard your vector databases from potential threats.

link:{#}[Learn about Database Security]


[.ds-row]
== Community & Support

=== Join the Conversation

Engage with our vibrant community of developers. Ask questions, share knowledge, or just hang out and chat about all things DataStax Astra.

link:{#}[Join on Discord] · link:{#}[Follow on X]

=== Need More Help?

* link:{#}[Ask the Astra community]
* link:{#}[Get in touch with support]