name: Bundle UI

on:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache .cache/npm
        uses: actions/cache@v2
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --quiet --no-progress --cache=.cache/npm

  verify:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use cached .cache/npm
        uses: actions/cache@v2
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Lint
        run: node_modules/.bin/gulp lint

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: verify
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use cached .cache/npm
        uses: actions/cache@v2
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Bundle
        run: node_modules/.bin/gulp bundle

      - name: Upload ui-bundle.zip
        uses: actions/upload-artifact@v2
        with:
          name: ui-bundle.zip
          path: build/ui-bundle.zip
